name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare environment
      run: rustup override set nightly && rustup component add rust-src && cargo install bootimage && rustup component add llvm-tools-preview
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose 
