name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare environment
      run: rustup target add x86_64-tin && rustup default nightly-x86_64-unknown-linux-gnu && rustup component add rust-src
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
